export const ErrorCodes = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION: "VALIDATION",
  CONFLICT: "CONFLICT",
  NEEDS_PURCHASE: "NEEDS_PURCHASE",
  NEEDS_AD: "NEEDS_AD",
  NEEDS_PREREQUISITE: "NEEDS_PREREQUISITE",
  EXPIRED: "EXPIRED",
  CANNOT_ACCESS: "CANNOT_ACCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REWARD_DENIED: "REWARD_DENIED",
  MAINTENANCE: "MAINTENANCE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
