/** Compact VN marketplace lexicon — not scraped from Facebook. Used to mint official Ad Library queries. */

export type MegaLex = {
  cores: readonly string[];
  flavors: readonly string[];
  mods: readonly string[];
};

export const COMMERCE_MODS: readonly string[] = [
  "chính hãng",
  "giá sỉ",
  "giá lẻ",
  "cao cấp",
  "giá rẻ",
  "bán chạy",
  "hàng mới",
  "nội địa trung",
  "nội địa nhật",
  "hàn quốc",
  "thái lan",
  "việt nam",
  "năm 2025",
  "năm 2026",
  "size mini",
  "full size",
  "không dây",
  "chống nước",
  "cảm ứng",
  "pin trâu",
  "hàng sẵn",
  "kho hà nội",
  "kho tphcm",
  "combo 2 hộp",
  "combo 3 hộp",
  "ship nội thành",
  "mua 1 tặng 1",
  "giá tại xưởng",
];

const BEAUTY_MODS = ["cho da dầu", "cho da khô", "cho da hỗn hợp", "ban đêm", "ban ngày", "nâng tone"];
const KID_MODS = ["sơ sinh", "cho bé", "size m", "size l", "mẹ bầu"];
const FASHION_MODS = ["form rộng", "oversize", "dáng ôm", "big size", "size s", "size xl"];
const TECH_MODS = ["type c", "sạc nhanh", "bluetooth", "wifi", "4k", "chống ồn"];

export const MEGA_LEXICON: Readonly<Record<string, MegaLex>> = {
  "my-pham": {
    cores: [
      "serum", "kem dưỡng", "toner", "sữa rửa mặt", "kem chống nắng", "mặt nạ", "tẩy trang",
      "kem nền", "phấn nước", "son tint", "son dưỡng", "mascara", "kẻ mắt", "kem mắt",
      "ampoule", "essence", "kem trị mụn", "tẩy tế bào chết", "dầu gội", "dầu xả",
      "kem dưỡng tóc", "thuốc nhuộm", "kem lót", "phấn phủ", "highlight má", "kem body",
      "sữa dưỡng thể", "tẩy da chết body", "xịt khoáng", "nước hoa hồng", "serum vitamin",
      "kem đêm", "kem ngày", "son môi", "chì kẻ mày", "gel vuốt tóc", "wax tóc",
      "dầu dưỡng tóc", "mặt nạ ngủ", "pad toner", "kem nâng tone",
    ],
    flavors: [
      "niacinamide", "retinol", "vitamin c", "hyaluronic", "aha bha", "centella", "tranexamic",
      "peptide", "collagen", "salicylic", "trà xanh", "gạo", "ốc sên", "nhau thai", "bakuchiol",
      "ceramide", "panthenol", "spf50", "spf30", "pa++++", "kiềm dầu", "cấp ẩm", "trắng da",
      "chống nhăn", "phục hồi", "se khít lỗ chân lông", "giảm thâm", "nám", "mụn ẩn",
      "nội địa trung", "hàn quốc", "nhật bản", "pháp", "10 phần trăm", "0.3 phần trăm",
      "30ml", "50ml", "100ml", "cho tuổi teen", "cho tuổi 30",
    ],
    mods: BEAUTY_MODS,
  },
  "cham-soc-ca-nhan": {
    cores: [
      "sữa tắm", "lăn khử mùi", "nước hoa", "dao cạo", "bàn chải điện", "kem đánh răng",
      "nước súc miệng", "sáp vuốt tóc", "máy sấy tóc", "lược điện", "máy tẩy lông",
      "bông tẩy trang", "gel rửa tay", "tăm nước", "bọt cạo râu", "nước hoa chiết",
      "sữa rửa mặt nam", "dầu gội khô", "kem chống hăm", "nước muối sinh lý",
      "máy cạo râu", "kéo cắt tóc", "bấm móng", "kem dưỡng tay", "sơn móng",
      "nước rửa kính áp tròng", "băng vệ sinh", "băng ngày", "dao cạo nữ", "wax lông",
      "sữa tắm nam", "sữa tắm nữ", "dầu gội dược liệu", "kem nẻ", "son dưỡng môi",
      "xịt thơm miệng", "chỉ nha khoa", "máy massage mặt", "máy rửa mặt", "bông rửa mặt",
    ],
    flavors: [
      "than hoạt tính", "trà xanh", "hoa hồng", "hoa nhài", "gỗ đàn hương", "cam bergamot",
      "bạc hà", "dừa", "yến mạch", "mật ong", "ion", "sóng siêu âm", "nam", "nữ",
      "unise", "mini", "50ml", "100ml", "200ml", "hương biển", "hương gỗ", "hương ngọt",
      "không cồn", "dịu nhẹ", "cho da nhạy cảm", "antibacterial", "fluoride", "than tre",
      "hàn quốc", "nhật bản", "pháp", "ý", "dubai", "chiết 10ml", "full 100ml",
    ],
    mods: [...BEAUTY_MODS, "cho nam", "cho nữ"],
  },
  tpcn: {
    cores: [
      "viên uống", "kẹo gummy", "sữa hạt", "whey protein", "collagen", "vitamin tổng hợp",
      "omega 3", "viên giảm cân", "sắt bà bầu", "men vi sinh", "đông trùng", "linh chi",
      "tinh chất nghệ", "viên trắng da", "viên mọc tóc", "canxi d3", "viên ngủ ngon",
      "bổ não", "sữa non", "lutein mắt", "glutathione", "dầu cá", "kẹo dẻo", "bột protein",
      "viên khớp", "viên gan", "viên tim", "kẹo sắt", "sữa tăng cân", "bột rau xanh",
      "viên enzyme", "trà giảm cân", "viên biotin", "kẽm", "magie", "vitamin d3",
      "bcaa", "creatine", "mass gainer", "pre workout",
    ],
    flavors: [
      "5000mg", "1000mg", "30 gói", "60 viên", "90 viên", "cho nữ", "cho nam", "cho bé",
      "hàn quốc", "nhật bản", "mỹ", "úc", "đức", "vị cam", "vị dâu", "không đường",
      "peptide", "thủy phân", "type 1", "type 3", "fish oil", "krill", "dha", "epa",
      "ban đêm", "ban ngày", "trước ăn", "sau ăn", "giảm mỡ", "tăng cơ", "đẹp da",
      "chống lão hóa", "tăng đề kháng", "bà bầu", "phụ nữ sau sinh", "người già",
    ],
    mods: ["chính hãng", "date xa", "hộp 30", "hộp 60"],
  },
  "thiet-bi-y-te": {
    cores: [
      "máy đo huyết áp", "máy đo đường huyết", "nhiệt kế", "máy xông mũi", "máy massage",
      "đai lưng", "máy trợ thính", "cân sức khỏe", "máy spo2", "ống nghe y tế",
      "máy hút mũi", "gối massage", "đèn hồng ngoại", "máy nén khí", "đai bụng",
      "máy đo tai", "máy xông tinh dầu y tế", "que thử đường", "kim lấy máu", "máy tăm nước y tế",
      "máy điện châm", "thảm massage", "máy kéo cổ", "nẹp cổ", "nẹp gối", "gậy chống",
      "xe lăn", "máy tạo oxy", "máy xông họng", "túi chườm", "đai nẹp cổ tay",
      "máy đo mỡ", "cân điện tử", "máy đo xương", "máy massage chân", "máy massage cổ",
      "máy massage mắt", "máy massage cầm tay", "máy massage gun", "súng massage",
    ],
    flavors: [
      "bắp tay", "cổ tay", "hồng ngoại", "không tiếp xúc", "omron", "microlife", "beurer",
      "pin sạc", "màn hình lớn", "giọng nói", "cho người già", "cho bé", "y tế gia đình",
      "cột sống", "thoát vị", "vai gáy", "bàn chân", "lưng", "cổ", "đầu gối",
      "6 đầu", "8 đầu", "32 cấp", "rung", "nhiệt", "airbag", "không dây",
      "phòng khám", "gia đình", "du lịch", "mini", "cao cấp",
    ],
    mods: ["bảo hành 12 tháng", "bảo hành 24 tháng", "có tem"],
  },
  "me-be": {
    cores: [
      "bỉm quần", "bỉm dán", "sữa công thức", "máy hút sữa", "bột ăn dặm", "máy hâm sữa",
      "ghế ăn dặm", "xe đẩy", "địu em bé", "nôi điện", "máy tiệt trùng", "bình sữa",
      "núm ty", "yếm ăn", "kem chống hăm", "khăn ướt", "xe tập đi", "ghế rung",
      "nệm chống trào", "máy pha sữa", "nước rửa bình", "tã vải", "sữa dê",
      "máy hút sữa không dây", "ghế ngồi ô tô", "nôi em bé", "quây cũi", "thảm chơi",
      "đồ chơi gặm nướu", "bàn chải bé", "sữa tắm gội bé", "dầu ẩm bé", "nước rôm",
      "bình tập uống", "thìa báo nóng", "máy xay ăn dặm", "nồi nấu cháo", "hộp trữ sữa",
      "túi trữ sữa", "máy tiệt trùng uv", "máy hâm bình", "đệm ngủ đúng tư thế",
    ],
    flavors: [
      "size n", "size s", "size m", "size l", "size xl", "sơ sinh", "0-6 tháng", "6-12 tháng",
      "số 1", "số 2", "số 3", "huggies", "merries", "bobby", "moony", "aptamil", "meiji",
      "friso", "vinamilk", "cổ rộng", "cổ hẹp", "thủy tinh", "ppsu", "silicon",
      "không dây", "đôi", "đơn", "vải mesh", "chống nắng", "gấp gọn",
      "cho mẹ", "sau sinh", "ăn dặm kiểu nhật", "organic",
    ],
    mods: KID_MODS,
  },
  "thu-cung": {
    cores: [
      "thức ăn hạt chó", "thức ăn hạt mèo", "pate chó", "pate mèo", "cát vệ sinh",
      "sữa tắm chó", "sữa tắm mèo", "vòng cổ chó", "vòng cổ mèo", "bàn cào",
      "nhà vệ sinh mèo", "xương gặm", "balo vận chuyển", "chuồng chó", "rọ mõm",
      "bát ăn tự động", "đồ chơi mèo", "đồ chơi chó", "sữa bột chó", "sữa bột mèo",
      "cát đậu nành", "thức ăn ướt", "snack chó", "snack mèo", "vòng chống ve",
      "thuốc nhỏ gáy", "sữa tắm trị ve", "lược chải lông", "kéo cắt móng", "tã chó",
      "quần áo chó", "dây dắt", "vòng yếm", "ổ đệm", "nhà gỗ chó", "cây mèo",
      "cỏ mèo", "cát bentonite", "máy lọc nước pet", "camera thú cưng",
    ],
    flavors: [
      "chó lớn", "chó nhỏ", "mèo trưởng thành", "mèo con", "poodle", "corgi", "husky",
      "ba tư", "anh lông ngắn", "hạt vị gà", "hạt vị cá", "hạt vị bò", "grain free",
      "hữu cơ", "royal canin", "whiskas", "pedigree", "hạt mix", "gói 1kg", "gói 2kg",
      "bao 5kg", "hương sữa", "không mùi", "vón cục", "khử mùi", "laser", "cỏ catnip",
    ],
    mods: ["cho chó", "cho mèo", "size nhỏ", "size lớn"],
  },
  "nha-cua": {
    cores: [
      "máy lọc không khí", "máy hút ẩm", "máy khuếch tán", "rèm cửa", "thảm trải sàn",
      "hộp đựng đồ", "kệ treo tường", "kệ giày", "đèn ngủ", "đèn bàn", "túi hút chân không",
      "móc treo", "kệ nhà tắm", "thảm lau chân", "hộp giấy ăn", "đèn led dây",
      "máy khử mùi", "túi đựng chăn", "rèm roman", "hộp quần áo", "kệ sách treo",
      "gương soi", "kệ trang điểm", "thùng rác", "cây lau nhà", "robot lau",
      "máy hút bụi giường", "túi thơm", "nến thơm", "đèn xông", "kệ góc",
      "thảm phòng khách", "thảm phòng ngủ", "rèm voan", "rèm vải", "thanh treo rèm",
      "móc dán tường", "hộp đựng remote", "kệ tivi treo", "ổ cắm nối dài",
    ],
    flavors: [
      "phòng ngủ", "phòng khách", "phòng tắm", "ban công", "căn hộ", "nhà ống",
      "vải canvas", "gỗ", "kim loại", "nhựa", "tre", "lông ngắn", "lông dài",
      "chống nắng", "cách nhiệt", "thấm hút", "chống trượt", "gấp gọn", "đa năng",
      "màu be", "màu xám", "màu trắng", "màu đen", "hoa văn", "trơn",
      "1m2", "1m6", "2m", "3m", "usb", "pin sạc",
    ],
    mods: ["gia đình", "căn hộ nhỏ", "phòng trọ"],
  },
  "nha-bep": {
    cores: [
      "nồi chiên không dầu", "kệ gia vị", "máy xay sinh tố", "chảo chống dính", "nồi inox",
      "máy ép chậm", "bình đun", "hộp cơm", "dao nhà bếp", "thớt gỗ", "nồi áp suất",
      "máy đánh trứng", "bếp từ", "hộp thực phẩm", "máy hút chân không", "chảo gang",
      "máy xay thịt", "ấm trà", "nồi lẩu điện", "máy làm kem", "máy làm sữa hạt",
      "nồi cơm điện", "chảo đá", "nồi đất", "dụng cụ gọt", "kéo bếp", "muỗng canh",
      "bộ nồi", "bộ dao", "máy hút mùi mini", "kệ úp chén", "giá để xoong",
      "hộp đựng gạo", "thùng rác bếp", "tấm chắn dầu", "cân nhà bếp", "nhiệt kế thực phẩm",
      "máy hút chân không thực phẩm", "túi hút chân không", "màng bọc", "giấy nến",
    ],
    flavors: [
      "6 lít", "8 lít", "4 lít", "3 lít", "inox 304", "chống dính", "bếp từ", "bếp gas",
      "locknlock", "sunhouse", "philips", "cuckoo", "hai ngăn", "một ngăn",
      "giữ nhiệt", "thủy tinh", "nhựa an toàn", "gỗ teak", "gỗ lim",
      "công suất lớn", "mini", "gia đình 4 người", "nhà hàng", "văn phòng",
      "kèm phụ kiện", "kèm công thức", "màn hình cảm ứng",
    ],
    mods: ["bảo hành chính hãng", "hàng trưng bày"],
  },
  "noi-that": {
    cores: [
      "sofa bed", "kệ sách gỗ", "bàn làm việc", "giường tầng", "tủ quần áo", "ghế gaming",
      "bàn trà", "tủ giày", "nệm foam", "ghế công thái học", "bàn nâng hạ", "tủ đầu giường",
      "giường hộp", "sofa góc", "kệ tivi", "bàn học", "nệm cao su", "tủ bếp",
      "ghế thư giãn", "bàn ăn", "ghế ăn", "tủ trưng bày", "giường đơn", "giường đôi",
      "tủ áo cánh lùa", "kệ trang trí", "bàn console", "ghế bar", "ghế thư giãn lưới",
      "nệm bông", "nệm lò xo", "gối cao su", "tấm bảo vệ nệm", "ga giường",
      "rèm phòng ngủ", "tủ giày thông minh", "bàn làm việc góc", "kệ hồ sơ",
      "tủ locker", "vách ngăn",
    ],
    flavors: [
      "gỗ công nghiệp", "gỗ tự nhiên", "sắt", "màu trắng", "màu óc chó", "màu đen",
      "1m2", "1m6", "1m8", "2m", "1 người", "2 người", "gia đình", "căn hộ",
      "gấp gọn", "thông minh", "hiện đại", "bắc âu", "nhật bản", "công thái học",
      "lưới", "da", "nỉ", "vải bố", "foam 15cm", "foam 20cm",
    ],
    mods: ["lắp ráp", "có sẵn", "đặt đóng"],
  },
  gadget: {
    cores: [
      "đèn led cảm ứng", "ổ cắm thông minh", "camera wifi", "chuông cửa camera",
      "đèn tủ bếp", "robot hút bụi", "khóa vân tay", "cảm biến chuyển động",
      "bóng đèn wifi", "máy chiếu mini", "công tắc thông minh", "đèn led dây",
      "bộ phát mesh", "camera ngoài trời", "đèn ngủ", "ổ cắm hẹn giờ",
      "remote hồng ngoại", "khóa thẻ từ", "camera 360", "ổ cắm wifi",
      "cảm biến cửa", "cảm biến khói", "ổn áp mini", "hub zigbee", "ổ cắm usb",
      "đèn led trồng rau", "máy đo không khí", "ổ cắm chống sét", "đèn pin siêu sáng",
      "sạc không dây bàn", "loa wifi", "màn hình cảm biến", "bảng vẽ", "bút trình chiếu",
      "chuột bay", "bàn phím gấp", "hub usb c", "dongle hdmi",
    ],
    flavors: [
      "tủ bếp", "trong nhà", "ngoài trời", "pin sạc", "năng lượng mặt trời", "usb",
      "wifi", "zigbee", "bluetooth", "alexa", "google home", "tuya", "yeelight",
      "3 màu", "16 triệu màu", "chống nước ip65", "độ phân giải 2k", "4k",
      "hồng ngoại", "màu đêm", "thẻ nhớ", "cloud", "không cần hub",
      "1 cổng", "4 cổng", "6 cổng", "hẹn giờ", "giọng nói",
    ],
    mods: TECH_MODS,
  },
  "dien-tu": {
    cores: [
      "ốp lưng iphone", "ốp lưng samsung", "tai nghe chống ồn", "sạc dự phòng",
      "cáp sạc", "loa bluetooth", "đồng hồ thông minh", "bàn phím cơ", "chuột không dây",
      "sạc nhanh", "sạc không dây", "cường lực", "giá đỡ điện thoại", "hub usb c",
      "bút cảm ứng", "tai nghe gaming", "smartwatch", "loa mini", "miếng dán màn",
      "cáp type c", "cáp iphone", "sạc 65w", "sạc 100w", "tai nghe inear",
      "tai nghe overear", "mic livestream", "ring light", "gimbal điện thoại",
      "thẻ nhớ", "usb 3.0", "ổ cứng di động", "ssd di động", "chuột gaming",
      "lót chuột", "giá đỡ laptop", "tản nhiệt laptop", "webcam", "microphone cài áo",
    ],
    flavors: [
      "iphone 15", "iphone 16", "iphone 14", "iphone 13", "samsung s24", "samsung s25",
      "xiaomi", "oppo", "vivo", "ipad", "tablet", "macbook", "laptop",
      "anc", "xuyên âm", "pin 20h", "pin 40h", "nam châm", "magsafe",
      "20.000mah", "10.000mah", "30.000mah", "led rgb", "switch red", "switch brown",
      "da pu", "nhựa cứng", "chống sốc", "trong suốt", "màu đen", "màu tím",
    ],
    mods: TECH_MODS,
  },
  "dien-may": {
    cores: [
      "máy giặt mini", "máy hút bụi", "quạt không cánh", "máy lọc nước", "nồi cơm điện",
      "máy sấy tóc", "bàn ủi hơi", "quạt tích điện", "máy hút ẩm", "quạt điều hòa",
      "máy sấy quần áo", "nồi cơm tách đường", "máy rửa bát", "bếp hồng ngoại",
      "máy hút mùi", "tủ lạnh mini", "máy giặt sấy", "máy hút bụi cầm tay",
      "máy xay sinh tố công nghiệp", "quạt trần", "quạt hộp", "máy nước nóng",
      "bình nóng lạnh", "máy lọc không khí", "máy hút bụi robot", "máy sấy giày",
      "máy hút chân không quần áo", "máy làm mát", "máy tạo ẩm", "máy sấy thực phẩm",
      "lò vi sóng", "lò nướng", "bếp từ đôi", "máy rửa chén", "máy giặt cửa trên",
      "máy giặt cửa trước", "tủ đông", "tủ mát", "máy đá viên", "máy ép trái cây",
    ],
    flavors: [
      "sunhouse", "sharp", "panasonic", "electrolux", "samsung", "lg", "xiaomi",
      "1 ngựa", "1.5 ngựa", "2 ngựa", "9kg", "8kg", "7kg", "inverter",
      "tiết kiệm điện", "gia đình", "văn phòng", "phòng trọ", "công suất lớn",
      "không dây", "pin lithium", "hepa", "lõi ro", "nóng lạnh",
      "20 lít", "30 lít", "50 lít", "90 lít",
    ],
    mods: ["bảo hành 12 tháng", "bảo hành 24 tháng"],
  },
  "thoi-trang-nu": {
    cores: [
      "đầm dự tiệc", "set bộ nữ", "váy body", "áo croptop", "jumpsuit", "đầm maxi",
      "quần jean nữ", "áo sơ mi nữ", "chân váy chữ a", "set đồ công sở", "áo khoác dạ",
      "váy xòe", "quần short nữ", "áo thun nữ", "đầm suông", "set đồ yoga",
      "áo khoác jean", "quần ống rộng", "áo len", "chân váy tennis", "đồ bộ mặc nhà",
      "áo hai dây", "áo blazer nữ", "quần tây nữ", "đầm chữ a", "váy yếm",
      "áo hoodie nữ", "áo cardigan", "chân váy dài", "set áo quần", "đầm ôm",
      "áo kiểu", "quần cullotes", "váy midi", "váy ngắn", "áo vest nữ",
      "áo khoác gió nữ", "set đồ đi biển", "đồ bơi nữ", "áo bra thể thao", "legging nữ",
    ],
    flavors: [
      "nữ", "công sở", "dự tiệc", "đi chơi", "mùa hè", "mùa đông", "mùa thu",
      "màu đen", "màu trắng", "màu be", "hoa nhí", "trơn", "kẻ sọc", "da",
      "lụa", "cotton", "jean", "nỉ", "len", "form rộng", "ôm body",
      "size s", "size m", "size l", "big size", "freestyle", "hàn quốc",
      "ulzzang", "vintage", "trẻ trung", "trung niên",
    ],
    mods: FASHION_MODS,
  },
  "thoi-trang-nam": {
    cores: [
      "áo polo nam", "sơ mi nam", "quần jean nam", "áo thun nam", "áo khoác gió",
      "set đồ nam", "áo hoodie", "áo khoác bomber", "quần tây nam", "áo nỉ nam",
      "blazer nam", "áo thun oversize", "quần jogger", "áo sơ mi kẻ", "set thể thao",
      "áo khoác da", "quần kaki", "áo polo thể thao", "áo vest nam", "quần short nam",
      "áo tank top", "áo len nam", "áo khoác dạ nam", "quần âu", "sơ mi trắng",
      "sơ mi denim", "áo flannel", "áo phao nam", "áo gile nam", "thắt lưng nam",
      "vớ nam", "mũ lưỡi trai", "mũ bucket", "áo mưa nam", "bộ vest nam",
      "áo thun cổ tròn", "áo thun cổ bẻ", "quần cargo", "quần short kaki", "áo khoác nỉ",
    ],
    flavors: [
      "nam", "công sở", "thể thao", "dạo phố", "màu đen", "màu trắng", "màu xanh",
      "cotton", "thun lạnh", "kaki", "jean", "da pu", "nỉ bông",
      "size m", "size l", "size xl", "size 2xl", "form rộng", "ôm",
      "in chữ", "trơn", "kẻ", "logo nhỏ", "cao cấp", "giá rẻ",
      "hàn quốc", "nhật", "âu", "big size",
    ],
    mods: FASHION_MODS,
  },
  "giay-dep": {
    cores: [
      "giày sneaker trắng", "dép quai ngang", "boot nữ", "giày chạy bộ", "dép tổ ong",
      "giày da nam", "sandal nữ", "giày búp bê", "giày thể thao nam", "dép cross",
      "giày lười nam", "sandal nam", "boot nam", "giày đế xuồng", "dép lê nữ",
      "giày bata", "giày da nữ", "dép kẹp nam", "giày soccer", "boot chelsea",
      "giày lười nữ", "giày cao gót", "giày bệt", "dép bánh mì", "giày boot nữ",
      "giày leo núi", "giày đá banh", "dép tổ ong nam", "giày slip on", "giày oxford",
      "giày derby", "giày sandal học sinh", "dép tổ ong nữ", "giày sneaker nam",
      "giày sneaker nữ", "boot cổ ngắn", "boot cổ cao", "giày da bò", "dép da",
    ],
    flavors: [
      "nam", "nữ", "unisex", "size 36", "size 38", "size 40", "size 42", "size 43",
      "màu trắng", "màu đen", "màu be", "da thật", "da pu", "vải canvas",
      "đế cao", "đế bệt", "chống trượt", "đi mưa", "đi học", "đi làm",
      "thể thao", "công sở", "hàn quốc", "nike style", "adidas style",
    ],
    mods: ["size nhỏ", "size lớn", "tặng tất"],
  },
  "tui-vi": {
    cores: [
      "túi đeo chéo da", "balo laptop", "ví da nam", "túi tote", "túi xách nữ",
      "ví card", "túi đựng laptop", "túi đeo hông", "túi đeo chéo nữ", "balo nữ",
      "clutch dự tiệc", "túi công sở", "ví dài nữ", "túi canvas", "balo chống nước",
      "túi máy ảnh", "ví mini", "túi đeo ngực", "balo học sinh", "túi trống du lịch",
      "túi xách tay", "balo nam", "ví cầm tay", "túi rút", "túi cói",
      "túi da bò", "balo bỉm sữa", "túi giữ nhiệt", "túi đựng giày", "túi gym",
      "cặp da nam", "cặp công sở", "túi đeo chéo nam", "ví vải", "túi phone",
      "balo kéo", "vali kéo", "túi xách du lịch", "túi đựng mỹ phẩm", "túi picnic",
    ],
    flavors: [
      "da thật", "da pu", "vải bố", "canvas", "chống nước", "laptop 14", "laptop 15",
      "màu đen", "màu nâu", "màu be", "nữ", "nam", "unise", "nhiều ngăn",
      "mini", "cỡ lớn", "hàn quốc", "ý", "công sở", "dạo phố", "du lịch",
    ],
    mods: ["tặng móc khóa", "kèm ví"],
  },
  "trang-suc": {
    cores: [
      "dây chuyền bạc", "bông tai nụ", "lắc tay", "nhẫn bạc", "vòng tay charm",
      "kính chống ánh sáng xanh", "kẹp tóc", "đồng hồ nữ", "dây chuyền titan",
      "bông tai dài", "nhẫn cặp", "lắc chân", "kính râm", "cài áo", "choker",
      "đồng hồ nam", "bông tai bạc", "nhẫn titan", "kính uv", "set trang sức",
      "lắc bạc", "dây chuyền vàng", "nhẫn vàng", "bông tai vàng", "vòng phong thủy",
      "vòng đá", "mặt phật", "dây chuyền chữ", "bông tai nụ đá", "lắc titan",
      "đồng hồ dây da", "đồng hồ dây kim loại", "kính cận", "gọng kính", "tròng kính",
      "cài tóc", "băng đô", "nhẫn adjust", "vòng tay nam", "dây chuyền nam",
    ],
    flavors: [
      "bạc 925", "titan", "vàng 18k", "vàng 10k", "ngọc trai", "đá cz", "pha lê",
      "nữ", "nam", "cặp đôi", "trẻ em", "không dị ứng", "mạ vàng",
      "hàn quốc", "ý", "phong thủy", "tỳ hưu", "cỏ 4 lá", "trái tim",
      "minimal", "cá tính", "công sở", "dự tiệc",
    ],
    mods: ["kèm hộp", "khắc tên"],
  },
  "thuc-pham": {
    cores: [
      "hạt điều rang muối", "nấm linh chi", "yến sào", "ngũ cốc", "bột protein",
      "mật ong", "nước mắm", "hạt macca", "khô bò", "hạt dinh dưỡng", "khô mực",
      "nấm hương", "bột cacao", "yến chưng", "hạt óc chó", "gia vị lẩu",
      "nấm đông cô", "bột rau má", "khô gà", "hạt chia", "nước mắm phú quốc",
      "hạt hạnh nhân", "hạt bí", "nho khô", "mơ sấy", "xoài sấy",
      "mít sấy", "chuối sấy", "thịt bò khô", "khô heo", "chà bông",
      "mắm tôm", "mắm nêm", "sa tế", "tương ớt", "nước tương",
      "bột nghệ", "bột gừng", "yến tinh chế", "nấm đông trùng", "nấm rơm khô",
    ],
    flavors: [
      "500g", "1kg", "250g", "hộp thiếc", "túi hút chân không", "rang muối",
      "rang không muối", "nguyên chất", "organic", "đắk lắk", "phú quốc",
      "rừng", "nhà làm", "không chất bảo quản", "vị cay", "vị ngọt",
      "cho bé", "ăn kiêng", "giàu đạm", "mix 5 loại", "mix 8 loại",
    ],
    mods: ["date xa", "hàng mới rang"],
  },
  "do-uong": {
    cores: [
      "cà phê rang xay", "trà sữa", "trà matcha", "cà phê hòa tan", "trà atiso",
      "nước ép cần tây", "bột cacao", "trà hoa cúc", "cà phê sữa đá", "trà gừng",
      "nước ép trái cây", "bột matcha", "cà phê túi lọc", "trà oolong", "nước yến",
      "sinh tố giảm cân", "trà thảo mộc", "cà phê cold brew", "nước ép lựu",
      "trà hoa hồng", "trà lài", "trà sen", "cà phê robusta", "cà phê arabica",
      "cà phê chồn", "trà shan tuyết", "nước mía", "nước dừa", "nước ép táo",
      "nước ép cam", "bột rau má", "cacao malaysia", "cacao indonesia", "trà sữa thái",
      "trà sữa trân châu", "cà phê muối", "cà phê trứng", "trà đào", "trà vải",
    ],
    flavors: [
      "đắk lắk", "buôn mê thuột", "nhật bản", "thái lan", "hàn quốc", "500g", "1kg",
      "túi 20 gói", "hộp 30", "nguyên chất", "không đường", "ít đường",
      "rang vừa", "rang đậm", "pha phin", "pha máy", "uống liền",
      "giảm cân", "detox", "cho văn phòng", "quán", "gia đình",
    ],
    mods: ["date xa", "rang mới"],
  },
  "o-to-xe-may": {
    cores: [
      "camera hành trình", "mũ bảo hiểm", "thảm lót sàn ô tô", "đèn bi cầu", "bơm lốp",
      "giá đỡ điện thoại xe", "áo mưa bộ", "nước rửa kính", "khóa đĩa", "mũ fullface",
      "dầu nhớt xe máy", "đèn trợ sáng", "bọc yên", "nước rửa xe", "camera lùi",
      "khóa cổ xe", "túi treo đầu xe", "sạc xe điện", "gương chiếu hậu", "áo mưa trong suốt",
      "thảm lót chân", "camera 4k", "mũ 3 4", "mũ nửa đầu", "găng tay xe máy",
      "kính mũ bảo hiểm", "bạt phủ xe", "túi chống nước xe", "đèn hậu", "xinhan xe",
      "còi xe", "khóa đĩa chống trộm", "thùng giữa xe", "thùng hông", "pad điện thoại",
      "nước làm mát", "bugi xe", "lọc gió", "nhớt 10w40", "camera gương",
    ],
    flavors: [
      "ô tô", "xe máy", "xe ga", "xe số", "honda", "yamaha", "toyota", "hyundai",
      "vinfast", "sh", "vision", "lead", "exciter", "winner",
      "4k", "2k", "wifi", "thẻ 64gb", "ban đêm", "gương cầu",
      "chống nước", "fullface", "3 4", "size m", "size l",
    ],
    mods: ["chính hãng", "bảo hành 12 tháng"],
  },
  "the-thao": {
    cores: [
      "thảm yoga", "tạ tay", "áo gym nam", "áo thể thao nữ", "dây kháng lực",
      "bình nước thể thao", "thảm tập bụng", "giày đá bóng", "lều cắm trại",
      "vợt pickleball", "dây nhảy", "con lăn bụng", "xe đạp tập", "túi ngủ",
      "vợt cầu lông", "bóng đá", "giày chạy trail", "áo compression", "thảm picnic",
      "gậy leo núi", "bình shaker", "tạ bình nước", "dây treo tập", "xà đơn",
      "thảm tập gym", "găng tay gym", "đai lưng gym", "vớ thể thao", "mũ lưỡi trai thể thao",
      "kính bơi", "đồ bơi nam", "đồ bơi nữ", "ván paddle", "bóng rổ",
      "vợt tennis", "bóng tennis", "thảm tập yoga chống trượt", "gạch yoga", "dây yoga",
    ],
    flavors: [
      "nam", "nữ", "2kg", "5kg", "10kg", "chống trượt", "dày 8mm", "dày 10mm",
      "cao su", "neoprene", "cotton", "dry fit", "size m", "size l",
      "người mới", "nâng cao", "phòng gym", "tại nhà", "dã ngoại",
      "1 người", "2 người", "gia đình", "pickelball", "yoga",
    ],
    mods: ["kèm túi", "kèm hướng dẫn"],
  },
  "khoa-hoc": {
    cores: [
      "khóa học excel", "tiếng anh giao tiếp", "ôn thi đại học", "khóa học marketing",
      "khóa học figma", "khóa học photoshop", "khóa học python", "khóa học kế toán",
      "khóa học ielts", "khóa học tiktok shop", "khóa học facebook ads", "khóa học ai",
      "khóa học content", "khóa học tiếng trung", "ôn thi toeic", "khóa học bán hàng",
      "khóa học kiếm tiền online", "khóa học thiết kế", "khóa học affiliate",
      "khóa học kế toán thuế", "khóa học word", "khóa học powerpoint", "khóa học data",
      "khóa học sql", "khóa học canva", "khóa học premiere", "khóa học capcut",
      "khóa học livestream", "khóa học shopee", "khóa học dropshipping",
      "ôn thi thpt", "ôn thi công chức", "khóa học toeic", "khóa học ielts 7.0",
      "tiếng anh trẻ em", "tiếng hàn giao tiếp", "tiếng nhật n5", "khóa học piano",
      "khóa học guitar", "khóa học vẽ",
    ],
    flavors: [
      "online", "offline", "buổi tối", "cuối tuần", "cấp tốc", "từ zero",
      "người mới", "nâng cao", "thực chiến", "kèm mentorship", "trọn đời",
      "2026", "hà nội", "tphcm", "đà nẵng", "live", "recorded",
      "cho sinh viên", "cho nhân sự", "cho chủ shop", "cho kế toán",
    ],
    mods: ["học thử", "cam kết đầu ra"],
  },
  "sach-vpp": {
    cores: [
      "sổ planner", "sách kỹ năng", "flashcard tiếng anh", "sách nuôi dạy con",
      "bút highlight", "sổ bullet journal", "bảng trắng mini", "sách tài chính",
      "sách marketing", "bút gel", "sổ tay bìa da", "sách đầu tư", "bảng flipchart",
      "bút lông dầu", "sách tâm lý", "flashcard kanji", "sổ còng", "bút máy",
      "sách nấu ăn", "giấy note", "sách tư duy", "sách bán hàng", "sách quản trị",
      "lịch để bàn", "lịch treo tường", "bìa hồ sơ", "kẹp file", "bút bi",
      "bút chì kim", "thước kẻ", "compa", "sách tô màu", "sách thiếu nhi",
      "sách tiếng anh", "từ điển", "vở ô ly", "giấy a4", "sổ lò xo",
      "bút dạ quang", "băng keo",
    ],
    flavors: [
      "2026", "2025", "tiếng việt", "tiếng anh", "bìa cứng", "bìa mềm",
      "a5", "a6", "a4", "màu đen", "màu be", "hàn quốc", "nhật",
      "người mới", "nâng cao", "cho bé", "cho văn phòng", "cho học sinh",
    ],
    mods: ["tặng bút", "bìa da"],
  },
  "do-choi": {
    cores: [
      "mô hình lắp ráp", "board game", "xếp hình nam châm", "xe điều khiển",
      "búp bê", "lego mini", "máy ảnh trẻ em", "slime", "súng nerf", "cát động lực",
      "mô hình gundam", "đồ chơi stem", "máy bay điều khiển", "rubik", "đồ chơi nhà bếp",
      "lego city", "búp bê barbie", "xe điều khiển từ xa", "đồ chơi giáo dục",
      "xếp hình", "mô hình xe", "mô hình máy bay", "đồ chơi gỗ", "puzzel",
      "trò chơi boardgame", "bài uno", "cờ tỷ phú", "cờ vua", "cờ caro",
      "đồ chơi bác sĩ", "đồ chơi siêu thị", "robot biến hình", "siêu nhân",
      "búp bê vải", "thú bông", "slime trong", "kính vr trẻ em", "máy chơi game cầm tay",
    ],
    flavors: [
      "trẻ em", "3 tuổi", "6 tuổi", "8 tuổi", "gia đình", "giáo dục",
      "nam châm", "gỗ", "nhựa abs", "pin sạc", "điều khiển", "2.4g",
      "1 144", "1 100", "mg", "hg", "rg", "3x3", "4x4",
      "bé trai", "bé gái", "stem", "montessori",
    ],
    mods: KID_MODS,
  },
  "nong-san": {
    cores: [
      "phân bón hữu cơ", "hạt giống rau", "béc tưới", "đất trồng rau", "chậu trồng cây",
      "đèn trồng cây", "thuốc trừ sâu sinh học", "máy cắt cỏ", "phân trùn quế",
      "tưới nhỏ giọt", "chậu treo", "đèn led trồng rau", "máy bơm mini", "hạt giống hoa",
      "giá thể lan", "keo liền sẹo", "lưới chắn côn trùng", "bình xịt", "kệ trồng rau",
      "hạt giống rau sạch", "phân npk", "phân gà", "phân cá", "chế phẩm em",
      "bẫy côn trùng", "màng phủ luống", "ống tưới", "van tưới", "máy gieo hạt",
      "kéo cắt cành", "cưa cành", "bình phun", "thùng ủ rác", "thùng trồng rau",
      "giàn leo", "lưới lan", "chậu sứ", "chậu nhựa", "đất sạch",
    ],
    flavors: [
      "rau muống", "rau cải", "xà lách", "cà chua", "ớt", "dưa leo", "hoa hồng",
      "lan", "bon sai", "sân thượng", "ban công", "vườn", "nhà phố",
      "hữu cơ", "vi sinh", "tan chậm", "5kg", "10kg", "20kg",
      "năng lượng mặt trời", "hẹn giờ", "tự động", "gia đình",
    ],
    mods: ["cho sân thượng", "cho ban công"],
  },
  khac: {
    cores: [
      "bộ dụng cụ đa năng", "đèn pin", "ổ khóa", "băng keo", "túi nilon",
      "thùng carton", "máy in nhiệt", "tem dán", "móc khóa", "ô dù",
      "bật lửa", "hộp quà", "túi giấy", "dây thừng", "keo 502",
      "keo 2 thành phần", "băng dính", "máy bắn keo", "dao rọc", "kéo văn phòng",
      "đèn đội đầu", "la bàn", "bình cứu hỏa mini", "khẩu trang", "găng tay y tế",
      "cồn 70", "nước rửa tay", "túi zipper", "hộp nhựa", "thùng nhựa",
    ],
    flavors: [
      "gia đình", "văn phòng", "du lịch", "xe hơi", "nhà kho", "bán sỉ",
      "chống nước", "siêu dính", "size lớn", "mini", "đa năng",
      "màu trong", "màu đen", "100 cái", "50 cái",
    ],
    mods: ["giá sỉ", "combo"],
  },
};

export function megaLexFor(slug: string): MegaLex {
  return MEGA_LEXICON[slug] ?? MEGA_LEXICON.khac ?? { cores: [], flavors: [], mods: [] };
}
