/** Extra product-name branches beyond LOCKED_NICHES.searchKeywords. User searches these on Ad Library. */
export const SCAN_BRANCHES: Readonly<Record<string, readonly string[]>> = {
  "my-pham": [
    "serum vitamin c",
    "serum hyaluronic acid",
    "kem dưỡng ẩm",
    "toner hoa hồng",
    "tẩy tế bào chết",
    "mặt nạ đất sét",
    "kem trị mụn",
    "son dưỡng môi",
    "kem nền kiềm dầu",
    "phấn nước cushion",
    "dầu gội giảm gàu",
    "dầu dưỡng tóc",
    "kem chống nắng body",
    "sữa rửa mặt trà xanh",
    "kem mắt chống nhăn",
    "tẩy trang micellar",
    "serum retinol",
    "kem dưỡng trắng da",
    "son tint bóng",
    "mascara dài mi",
    "nước hoa hồng",
    "ampoule phục hồi",
    "kem chống nắng nâng tone",
    "dầu gội phủ bạc",
    "mặt nạ ngủ",
    "tẩy da chết môi",
    "kem lót kiềm dầu",
    "phấn phủ bột",
  ],
  "cham-soc-ca-nhan": [
    "lăn khử mùi nam",
    "sữa tắm trắng da",
    "dao cạo râu",
    "máy tẩy lông",
    "nước hoa nữ",
    "kem đánh răng than",
    "bông tẩy trang",
    "nước muối sinh lý",
    "bàn chải điện",
    "nước súc miệng",
    "sáp vuốt tóc",
    "dầu gội khô",
    "kem chống hăm người lớn",
    "gel rửa tay khô",
    "dao cạo nữ",
    "lăn khử mùi nữ",
    "sữa tắm nam",
    "nước hoa chiết",
    "bọt cạo râu",
    "tăm nước",
    "máy sấy tóc ion",
    "lược điện duỗi tóc",
  ],
  "tpcn": [
    "viên uống collagen",
    "kẹo gummy vitamin",
    "sữa hạt tăng cân",
    "viên uống giảm cân",
    "đông trùng hạ thảo",
    "tinh chất nghệ",
    "men vi sinh",
    "sắt cho bà bầu",
    "viên uống trắng da",
    "omega 3 fish oil",
    "vitamin tổng hợp",
    "whey protein",
    "viên uống glutathione",
    "dầu cá omega",
    "kẹo dẻo collagen",
    "viên uống mọc tóc",
    "canxi vitamin d3",
    "viên uống ngủ ngon",
    "tinh dầu thông đỏ",
    "nấm linh chi viên",
    "viên uống bổ não",
    "kẹo gummy trẻ em",
    "sữa non colostrum",
    "viên uống mắt lutein",
  ],
  "thiet-bi-y-te": [
    "máy đo đường huyết",
    "máy xông mũi",
    "máy massage mắt",
    "đai lưng cột sống",
    "máy trợ thính",
    "máy hút mũi em bé",
    "cân sức khỏe",
    "máy đo huyết áp",
    "máy massage cổ",
    "nhiệt kế hồng ngoại",
    "máy massage cầm tay",
    "máy xông tinh dầu y tế",
    "máy đo spo2",
    "đai massage bụng",
    "máy nén khí trị liệu",
    "gối massage cổ",
    "máy đo đường huyết que thử",
    "ống nghe y tế",
    "máy massage chân",
    "đèn hồng ngoại trị liệu",
  ],
  "me-be": [
    "bỉm dán sơ sinh",
    "nước rửa bình sữa",
    "ghế ăn dặm",
    "xe đẩy em bé",
    "máy tiệt trùng bình",
    "kem chống hăm",
    "yếm ăn dặm",
    "nôi điện em bé",
    "bỉm quần",
    "máy hút sữa",
    "sữa công thức",
    "bột ăn dặm",
    "máy hâm sữa",
    "địu em bé",
    "ghế rung em bé",
    "tã vải sơ sinh",
    "sữa dê công thức",
    "núm ty thay thế",
    "máy hút sữa không dây",
    "xe tập đi",
    "nệm chống trào ngược",
    "khăn ướt em bé",
    "bình sữa cổ rộng",
    "máy pha sữa",
  ],
  "thu-cung": [
    "pate cho mèo",
    "xương gặm cho chó",
    "nhà vệ sinh mèo",
    "vòng cổ chống ve",
    "bàn cào móng",
    "sữa bột cho chó",
    "thức ăn hạt chó",
    "cát vệ sinh mèo",
    "sữa tắm thú cưng",
    "thức ăn hạt mèo",
    "pate cho chó",
    "vòng cổ chó",
    "balo vận chuyển mèo",
    "đồ chơi mèo laser",
    "sữa tắm chó",
    "cát đậu nành mèo",
    "thức ăn ướt mèo",
    "rọ mõm chó",
    "chuồng chó gấp",
    "bát ăn tự động",
  ],
  "nha-cua": [
    "máy khuếch tán tinh dầu",
    "kệ treo tường",
    "rèm cửa chống nắng",
    "túi hút chân không",
    "đèn ngủ cảm ứng",
    "hộp đựng quần áo",
    "máy lọc không khí",
    "hộp đựng đồ",
    "thảm trải sàn",
    "máy hút ẩm phòng",
    "đèn bàn học",
    "kệ giày thông minh",
    "túi đựng chăn ga",
    "móc treo quần áo",
    "máy khuếch tán phòng",
    "rèm roman",
    "thảm lau chân",
    "hộp giấy ăn",
    "kệ nhà tắm",
    "đèn led dây",
  ],
  "nha-bep": [
    "chảo chống dính",
    "máy ép chậm",
    "bình đun siêu tốc",
    "hộp cơm giữ nhiệt",
    "dao nhà bếp",
    "máy làm sữa hạt",
    "thớt gỗ kháng khuẩn",
    "nồi chiên không dầu",
    "kệ gia vị",
    "máy xay sinh tố",
    "nồi áp suất điện",
    "máy đánh trứng",
    "bếp từ đơn",
    "hộp đựng thực phẩm",
    "máy hút chân không thực phẩm",
    "chảo gang",
    "nồi inox 3 đáy",
    "máy xay thịt",
    "ấm trà infuser",
    "dụng cụ gọt rau",
    "máy làm kem",
    "nồi lẩu điện",
  ],
  "noi-that": [
    "giường tầng",
    "tủ quần áo",
    "ghế gaming",
    "bàn trà sofa",
    "tủ giày thông minh",
    "nệm foam",
    "sofa bed",
    "kệ sách gỗ",
    "bàn làm việc",
    "ghế công thái học",
    "bàn nâng hạ",
    "tủ đầu giường",
    "giường hộp",
    "ghế sofa góc",
    "kệ tivi",
    "bàn học sinh",
    "nệm cao su",
    "tủ bếp gỗ",
    "ghế thư giãn",
    "bàn ăn thông minh",
  ],
  gadget: [
    "camera wifi trong nhà",
    "chuông cửa camera",
    "đèn ngủ projector",
    "robot hút bụi mini",
    "ổ cắm wifi",
    "khóa cửa vân tay",
    "đèn led cảm ứng",
    "ổ cắm thông minh",
    "đèn tủ bếp",
    "đèn led cảm ứng tủ",
    "cảm biến chuyển động",
    "ổ cắm hẹn giờ",
    "bóng đèn wifi",
    "camera ngoài trời",
    "máy chiếu mini",
    "remote hồng ngoại wifi",
    "công tắc thông minh",
    "đèn led dây wifi",
    "bộ phát wifi mesh",
    "khóa cửa thẻ từ",
    "camera 360 độ",
    "đèn ngủ mặt trăng",
  ],
  "dien-tu": [
    "cáp sạc type c",
    "sạc dự phòng",
    "loa bluetooth",
    "đồng hồ thông minh",
    "miếng dán màn hình",
    "bàn phím cơ",
    "chuột không dây",
    "ốp lưng iphone",
    "tai nghe chống ồn",
    "sạc nhanh",
    "tai nghe bluetooth",
    "sạc không dây",
    "cáp sạc iphone",
    "ốp lưng samsung",
    "loa mini",
    "smartwatch nữ",
    "bút cảm ứng tablet",
    "hub usb c",
    "tai nghe gaming",
    "sạc dự phòng nam châm",
    "giá đỡ điện thoại",
    "cường lực iphone",
  ],
  "dien-may": [
    "máy lọc nước",
    "nồi cơm điện",
    "máy sấy tóc",
    "bàn ủi hơi nước",
    "quạt tích điện",
    "máy hút ẩm",
    "máy giặt mini",
    "máy hút bụi",
    "quạt không cánh",
    "máy lọc không khí",
    "máy hút bụi cầm tay",
    "quạt điều hòa",
    "máy sấy quần áo",
    "nồi cơm tách đường",
    "máy xay sinh tố công nghiệp",
    "máy rửa bát mini",
    "bếp hồng ngoại",
    "máy hút mùi",
    "tủ lạnh mini",
    "máy giặt sấy",
  ],
  "thoi-trang-nu": [
    "áo khoác jean nữ",
    "quần ống rộng",
    "áo len nữ",
    "chân váy tennis",
    "đồ bộ mặc nhà",
    "áo hai dây",
    "đầm dự tiệc",
    "set bộ nữ",
    "váy body",
    "áo croptop",
    "jumpsuit nữ",
    "đầm maxi",
    "quần jean nữ",
    "áo sơ mi nữ",
    "chân váy chữ a",
    "set đồ công sở",
    "áo khoác dạ nữ",
    "váy xòe",
    "quần short nữ",
    "áo thun nữ",
    "đầm suông",
    "set đồ tập yoga",
  ],
  "thoi-trang-nam": [
    "áo thun nam",
    "quần short nam",
    "áo khoác gió nam",
    "set đồ nam",
    "áo hoodie nam",
    "áo polo nam",
    "sơ mi nam",
    "quần jean nam",
    "áo khoác bomber nam",
    "quần tây nam",
    "áo nỉ nam",
    "blazer nam",
    "áo thun oversize nam",
    "quần jogger nam",
    "áo sơ mi kẻ nam",
    "set đồ thể thao nam",
    "áo khoác da nam",
    "quần kaki nam",
    "áo polo thể thao",
    "áo vest nam",
  ],
  "giay-dep": [
    "giày chạy bộ",
    "dép tổ ong",
    "giày da nam",
    "sandal nữ",
    "giày búp bê",
    "giày sneaker trắng",
    "dép quai ngang",
    "boot nữ",
    "giày thể thao nam",
    "dép cross",
    "giày lười nam",
    "sandal nam",
    "boot nam cổ cao",
    "giày đế xuồng",
    "dép lê nữ",
    "giày bata",
    "giày da nữ",
    "dép kẹp nam",
    "giày soccer",
    "boot chelsea",
  ],
  "tui-vi": [
    "túi tote vải",
    "túi xách nữ",
    "ví card holder",
    "túi đựng laptop",
    "túi đeo hông",
    "túi đeo chéo da",
    "balo laptop",
    "ví da nam",
    "túi đeo chéo nữ",
    "balo nữ",
    "clutch dự tiệc",
    "túi xách công sở",
    "ví dài nữ",
    "túi canvas",
    "balo chống nước",
    "túi đựng máy ảnh",
    "ví mini nữ",
    "túi đeo ngực",
    "balo học sinh",
    "túi trống du lịch",
  ],
  "trang-suc": [
    "nhẫn bạc nữ",
    "vòng tay charm",
    "kính mắt chống ánh sáng xanh",
    "kẹp tóc ngọc trai",
    "đồng hồ nữ",
    "dây chuyền bạc",
    "bông tai nụ",
    "lắc tay",
    "dây chuyền titan",
    "bông tai dài",
    "nhẫn cặp",
    "lắc chân bạc",
    "kính râm nữ",
    "cài áo",
    "vòng cổ choker",
    "đồng hồ nam dây da",
    "bông tai bạc",
    "nhẫn titan",
    "kính chống tia uv",
    "set trang sức bạc",
  ],
  "thuc-pham": [
    "ngũ cốc ăn sáng",
    "bột protein",
    "mật ong rừng",
    "nước mắm nhĩ",
    "hạt macca",
    "khô bò",
    "hạt điều rang muối",
    "nấm linh chi",
    "yến sào",
    "hạt dinh dưỡng mix",
    "khô mực",
    "nấm hương khô",
    "bột cacao nguyên chất",
    "yến chưng sẵn",
    "hạt óc chó",
    "mật ong hoa nhãn",
    "gia vị lẩu",
    "nấm đông cô",
    "bột rau má",
    "khô gà lá chanh",
    "hạt chia",
    "nước mắm phú quốc",
  ],
  "do-uong": [
    "cà phê hòa tan",
    "trà atiso",
    "nước ép cần tây",
    "bột cacao",
    "trà hoa cúc",
    "cà phê rang xay",
    "trà sữa",
    "trà matcha",
    "cà phê sữa đá",
    "trà gừng mật ong",
    "nước ép trái cây",
    "bột matcha nhật",
    "cà phê túi lọc",
    "trà oolong",
    "nước yến",
    "sinh tố giảm cân",
    "trà thảo mộc",
    "cà phê cold brew",
    "nước ép lựu",
    "bột cacao malaysia",
  ],
  "o-to-xe-may": [
    "đèn bi cầu ô tô",
    "bơm lốp ô tô",
    "giá đỡ điện thoại xe máy",
    "áo mưa bộ",
    "nước rửa kính ô tô",
    "khóa đĩa xe máy",
    "camera hành trình",
    "mũ bảo hiểm",
    "thảm lót sàn ô tô",
    "mũ bảo hiểm fullface",
    "camera hành trình 4k",
    "dầu nhớt xe máy",
    "thảm lót chân ô tô",
    "đèn trợ sáng xe máy",
    "bọc yên xe máy",
    "nước rửa xe",
    "camera lùi ô tô",
    "khóa cổ xe máy",
    "túi treo đầu xe",
    "sạc xe máy điện",
    "gương chiếu hậu ô tô",
    "áo mưa trong suốt",
  ],
  "the-thao": [
    "dây kháng lực",
    "bình nước thể thao",
    "thảm tập bụng",
    "giày đá bóng",
    "lều cắm trại",
    "vợt pickleball",
    "thảm yoga",
    "tạ tay",
    "áo gym nam",
    "áo thể thao nữ",
    "dây nhảy thể dục",
    "con lăn tập bụng",
    "xe đạp tập",
    "túi ngủ cắm trại",
    "vợt cầu lông",
    "bóng đá size 5",
    "giày chạy trail",
    "áo compression",
    "thảm picnic",
    "gậy leo núi",
    "bình shaker",
    "tạ bình nước",
  ],
  "khoa-hoc": [
    "khóa học marketing",
    "khóa học kiếm tiền online",
    "khóa học thiết kế",
    "khóa học IELTS",
    "khóa học kế toán",
    "khóa học excel",
    "tiếng anh giao tiếp",
    "ôn thi đại học",
    "khóa học facebook ads",
    "khóa học tiktok shop",
    "khóa học figma",
    "khóa học photoshop",
    "khóa học python",
    "khóa học kiếm tiền affiliate",
    "ôn thi toeic",
    "khóa học bán hàng",
    "khóa học content",
    "khóa học tiếng trung",
    "khóa học AI",
    "khóa học kế toán thuế",
  ],
  "sach-vpp": [
    "sách nuôi dạy con",
    "bút highlight",
    "sổ bullet journal",
    "bảng trắng mini",
    "sách tài chính",
    "sổ planner",
    "sách kỹ năng",
    "flashcard tiếng anh",
    "sách marketing",
    "bút gel",
    "sổ tay bìa da",
    "sách đầu tư",
    "bảng flipchart",
    "bút lông dầu",
    "sách tâm lý",
    "flashcard kanji",
    "sổ còng planner",
    "bút máy",
    "sách dạy nấu ăn",
    "giấy note",
  ],
  "do-choi": [
    "slime đồ chơi",
    "xe điều khiển",
    "búp bê",
    "lego mini",
    "máy ảnh trẻ em",
    "xếp hình nam châm",
    "mô hình lắp ráp",
    "board game",
    "đồ chơi giáo dục",
    "xe điều khiển từ xa",
    "búp bê barbie",
    "lego city",
    "súng nerf",
    "đồ chơi cát động lực",
    "mô hình gundam",
    "board game gia đình",
    "đồ chơi STEM",
    "máy bay điều khiển",
    "rubik 3x3",
    "đồ chơi nhà bếp trẻ em",
  ],
  "nong-san": [
    "đất trồng rau",
    "chậu trồng cây",
    "đèn trồng cây",
    "thuốc trừ sâu sinh học",
    "máy cắt cỏ mini",
    "phân bón hữu cơ",
    "hạt giống rau",
    "béc tưới",
    "hạt giống rau sạch",
    "phân trùn quế",
    "hệ thống tưới nhỏ giọt",
    "chậu treo",
    "đèn led trồng rau",
    "máy bơm mini vườn",
    "hạt giống hoa",
    "giá thể trồng lan",
    "keo liền sẹo cây",
    "lưới chắn côn trùng",
    "bình xịt tưới cây",
    "kệ trồng rau",
  ],
};
