import { afterEach, describe, expect, it } from "vitest";
import {
  NANO_BANANA_MISSING_KEY,
  NANO_BANANA_MODEL,
  generateNanoBananaStill,
  nanoBananaGenerateUrl,
  nanoBananaStillPrompt,
  parseNanoBananaImage,
} from "./nano-banana";

describe("nano banana stills", () => {
  const prev = process.env.GEMINI_API_KEY;

  afterEach(() => {
    if (prev === undefined) delete process.env.GEMINI_API_KEY;
    else process.env.GEMINI_API_KEY = prev;
  });

  it("builds a still prompt without a nameplate", () => {
    const prompt = nanoBananaStillPrompt({
      name: "Cô Minh",
      look: "teacher",
      bible: "Same photoreal Vietnamese teacher.",
    });
    expect(prompt).toMatch(/16:9/);
    expect(prompt).toMatch(/Cô Minh/);
    expect(prompt).toMatch(/no nameplate/i);
    expect(nanoBananaGenerateUrl("abc")).toContain("gemini-2.5-flash-image:generateContent");
  });

  it("parses inline image bytes", () => {
    const bytes = Buffer.alloc(80, 7);
    const parsed = parseNanoBananaImage({
      candidates: [{ content: { parts: [{ inlineData: { mimeType: "image/png", data: bytes.toString("base64") } }] } }],
    });
    expect(parsed.contentType).toBe("image/png");
    expect(parsed.bytes.equals(bytes)).toBe(true);
    expect(() => parseNanoBananaImage({ candidates: [{ content: { parts: [{ text: "hi" }] } }] })).toThrow(/không trả file ảnh/);
  });

  it("requires a Gemini key and returns generated bytes", async () => {
    delete process.env.GEMINI_API_KEY;
    await expect(
      generateNanoBananaStill({ name: "Lan", look: "teacher", bible: "Same face." }),
    ).rejects.toThrow(NANO_BANANA_MISSING_KEY);

    process.env.GEMINI_API_KEY = "test-gemini";
    const png = Buffer.alloc(80, 9);
    const result = await generateNanoBananaStill({
      name: "Lan",
      look: "teacher",
      bible: "Same face.",
      fetchImpl: async () =>
        new Response(
          JSON.stringify({
            candidates: [{ content: { parts: [{ inlineData: { mimeType: "image/png", data: png.toString("base64") } }] } }],
          }),
          { status: 200 },
        ),
    });
    expect(result.provider).toBe("nano_banana");
    expect(result.model).toBe(NANO_BANANA_MODEL);
    expect(result.bytes.equals(png)).toBe(true);
  });
});
